server:
  port: 2002
  servlet:
    context-path: /api/v1

spring:
  application:
    name: tour
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/${DB_NAME:dev_database}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:my_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  jwt:
    secret: ZHJhZ29uIGlzIHZlcnkgaGFuZHNvbWUgYW5kIGZyaWVuZGx5
    expiration-time: 
      access-token: 18000000
      refresh-token: 864000000
