server:
  port: 2002
  servlet:
    context-path: /api/v1

spring:
  application:
    name: tour
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:5432/${POSTGRES_DB:dev_database}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:my_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  jwt:
    secret: ZHJhZ29uIGlzIHZlcnkgaGFuZHNvbWUgYW5kIGZyaWVuZGx5
    expiration-time: 
      access-token: 18000000
      refresh-token: 864000000
  kafka: 
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    topics:
      user-update:
        name: ${USER-UPDATE:USER-UPDATE-DEV}


