services:
  mongo:
    image: mongo:7.0.15
    container_name: mongodb
    ports:
      - "27018:27017"
    env_file:
      - .env
    networks:
      - general-network
    volumes:
      - mongo-data:/data/db
    # restart: always

networks:
  general-network:
    name: general-network

volumes:
  mongo-data:
    name: mongo-data