services:
  tour-service:
    build: 
      context: ./tour
    container_name: tour-service
    image: tour-service
    ports:
      - "2002:2002" 
    env_file:
      - .env
    networks:
      - general-network
  lead-service:
    build: 
      context: ./leadservice
    container_name: lead-service
    image: lead-service
    ports:
      - "2003:2003" 
    env_file:
      - .env
    networks:
      - general-network

networks:
  general-network:
    name: general-network