DROP TYPE IF EXISTS EnumRoleName CASCADE;
CREATE TYPE EnumRoleName AS ENUM ('ADMIN', 'USER');

CREATE TABLE IF NOT EXISTS role (
    id UUID PRIMARY KEY,
    name EnumRoleName NOT NULL UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);